### ISSUE TITLE
parametri per finestre dati storici

### ISSUE THREAD

**Issue by enriconardelli** [enriconardelli/APP-visuali#13]
Aggiungere una checkbox "avanzate" per visualizzare anche di dati di dettaglio
Aggiungere un doropdown menu per scegliere quanti dati storici visualizzare

**Comment by marco-ciamb** [comment]
risolto in commit 7efb491fecc4f8ef344a23ceebcfb98d4d0b9238

**Comment by marco-ciamb** [comment]
Risolto bug in d2cb39e047ab96e204b1ae0b5243ce3686b67ef2
