### ISSUE TITLE
previsioni più realistiche

### ISSUE THREAD

**Issue by enriconardelli** [enriconardelli/APP-visuali#16]
- la classe delle previsioni deve poter mantenere più dati storici
- funzione di previsione basata sugli ultimi N dati storici

**Comment by marco-ciamb** [comment]
Ho aggiunto dei database alla classe VISUALIZZA_METEO_PREVISIONE e ho implementato una previsione basata sulla retta ai minimi quadrati degli ultimi N valori (N=5)
