### ISSUE TITLE
diagramma delle classi

### ISSUE THREAD

**Issue by enriconardelli** [enriconardelli/APP-visuali#17]
generare un diagramma delle classi "rilevanti"

**Comment by enriconardelli** [comment]
![diagramma-classi-3-apr-17-20](https://github.com/enriconardelli/APP-visuali/assets/7966242/241abedc-9362-4d72-99d3-b5b222d38045)

**Comment by marco-ciamb** [comment]
![START](https://github.com/enriconardelli/APP-visuali/assets/142524136/a2066b64-eb4c-460b-a0ab-17ed55ceb268)
Struttura attuale (Commit 301b8ec6431488791d5d7cce7828d566cbadd57b)
